# Generated by Django 4.2.1 on 2023-06-13 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_uploadmedia_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadmedia',
            table='myapp_uploadmedia',
        ),
    ]
